### ISSUE TITLE
v1 compatibility

### ISSUE THREAD

**Issue by pacharrin** [serverless-examples/serverless-cd-example#12]
Thanks for the great sample, i was wondering if you have experience with v1 of serverless, alot have changed and i am having trouble getting this to work on the latest version.

**Comment by johncmckim** [comment]
Hi @pacharrin sorry for the slow response. I know it's probably too late. But there is an example in this repo but it's probably a little out of date. For starters `serverless.env.yml` doesn't exist anymore. I have done a write-up [on medium](https://serverless.zone/ci-cd-with-serverless-v1-0-0-beta-ccb332944c6) but again it's a little out of date.

I might try do another write up next year. Just have to find the time.
